'use strict';
// Concatenate ASCII City's sources (tools/city-manifest.json) into ascii-city.bundle.js.
// One classic script, same as sleep-os.bundle.js: top-level declarations share one scope and
// load order is the manifest order. "pure" files must not touch the DOM at load time, so the
// node tests can run them in a vm (test/helpers/load-city.cjs); "dom" files come after.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'ascii-city.bundle.js');
const MANIFEST = path.join(__dirname, 'city-manifest.json');

const readCityManifest = () => JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
const read = rel => fs.readFileSync(path.join(ROOT, rel), 'utf8');

function buildCity() {
  const m = readCityManifest();
  return '// GENERATED by tools/build-city.cjs from city/*.js - edit those, then npm run build\n' +
    [...m.pure, ...m.dom].map(read).join('');
}

module.exports = { buildCity, readCityManifest, OUT };

if (require.main === module) {
  const out = buildCity();
  fs.writeFileSync(OUT, out);
  console.log('built ascii-city.bundle.js: ' + Buffer.byteLength(out) + ' bytes');
}
